host = "localhost"
port = 3002

// array of usernames
admins = [
  "user1"
]

[repo]

conn = "postgres://nsteenla:@localhost:5432/dilliver_dev?sslmode=disable"

[storage]

conn = "https://id:secret@endpoint/bucket?region=region"

[oidc]

url = ""
id = ""
secret = ""
redirect_url = "http://localhost:3002/auth/callback"

[cookies]

// 32 byte random string
secret = ""
