version: "3.9"

services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      DELIVER_ENV: local
      DELIVER_HOST: ""
      DELIVER_PORT: 3000
      DELIVER_ADMINS: "CHANGEME"
      DELIVER_REPO_CONN: "postgres://deliver:deliver@postgres:5432/deliver?sslmode=disable"
      DELIVER_STORAGE_CONN: "http://minio:minio@minio:9000/deliver"
      DELIVER_OIDC_URL: "CHANGEME"
      DELIVER_OIDC_ID: "CHANGEME"
      DELIVER_OIDC_SECRET: "CHANGEME"
      DELIVER_OIDC_REDIRECT_URL: "http://localhost:3000/auth/callback"
      DELIVER_COOKIE_SECRET: "1234"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - minio
    command:
      - sh
      - -c
      - |
        /dist/tern migrate
        /dist/app server

  postgres:
    image: postgres:16-alpine
    ports:
      - 5432
    user: postgres
    environment:
      POSTGRES_DB: deliver
      POSTGRES_USER: deliver
      POSTGRES_PASSWORD: deliver
    volumes:
      - ~/tmp/deliver_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U deliver -d deliver"]
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2023-12-09T18-17-51Z
    ports:
      - 9000
      - 9001
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ~/tmp/deliver_minio_data:/data
