// Code generated by qtc from "edit_folder.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/edit_folder.qtpl:1
package views

//line views/edit_folder.qtpl:1
import "github.com/ugent-library/deliver/ctx"

//line views/edit_folder.qtpl:2
import "github.com/ugent-library/deliver/models"

//line views/edit_folder.qtpl:3
import "github.com/ugent-library/deliver/validate"

//line views/edit_folder.qtpl:5
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/edit_folder.qtpl:5
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/edit_folder.qtpl:6
type EditFolder struct {
	Folder           *models.Folder
	ValidationErrors *validate.Errors
}

//line views/edit_folder.qtpl:12
func (v *EditFolder) StreamTitle(qw422016 *qt422016.Writer, c *ctx.Ctx) {
//line views/edit_folder.qtpl:12
	qw422016.E().S(v.Folder.Space.Name)
//line views/edit_folder.qtpl:12
	qw422016.N().S(` - Edit `)
//line views/edit_folder.qtpl:12
	qw422016.E().S(v.Folder.Name)
//line views/edit_folder.qtpl:12
}

//line views/edit_folder.qtpl:12
func (v *EditFolder) WriteTitle(qq422016 qtio422016.Writer, c *ctx.Ctx) {
//line views/edit_folder.qtpl:12
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/edit_folder.qtpl:12
	v.StreamTitle(qw422016, c)
//line views/edit_folder.qtpl:12
	qt422016.ReleaseWriter(qw422016)
//line views/edit_folder.qtpl:12
}

//line views/edit_folder.qtpl:12
func (v *EditFolder) Title(c *ctx.Ctx) string {
//line views/edit_folder.qtpl:12
	qb422016 := qt422016.AcquireByteBuffer()
//line views/edit_folder.qtpl:12
	v.WriteTitle(qb422016, c)
//line views/edit_folder.qtpl:12
	qs422016 := string(qb422016.B)
//line views/edit_folder.qtpl:12
	qt422016.ReleaseByteBuffer(qb422016)
//line views/edit_folder.qtpl:12
	return qs422016
//line views/edit_folder.qtpl:12
}

//line views/edit_folder.qtpl:14
func (v *EditFolder) StreamContent(qw422016 *qt422016.Writer, c *ctx.Ctx) {
//line views/edit_folder.qtpl:14
	qw422016.N().S(`
    <div class="w-100 u-scroll-wrapper">
        <div class="bg-white">
            <div class="bc-navbar bc-navbar--xlarge bc-navbar--white bc-navbar--bordered-bottom">
                <div class="bc-toolbar">
                    <div class="bc-toolbar-left">
                        <div class="bc-toolbar-item">
                            <h4 class="bc-toolbar-title">
                                <a href="`)
//line views/edit_folder.qtpl:22
	qw422016.E().S(c.PathTo("space", "spaceName", v.Folder.Space.Name).String())
//line views/edit_folder.qtpl:22
	qw422016.N().S(`">
                                    <i class="if if-arrow-left"></i>
                                    <span>`)
//line views/edit_folder.qtpl:24
	qw422016.E().S(v.Folder.Space.Name)
//line views/edit_folder.qtpl:24
	qw422016.N().S(`</span>
                                </a>
                                <span>&mdash; Edit folder</span>
                                <a href="`)
//line views/edit_folder.qtpl:27
	qw422016.E().S(c.PathTo("folder", "folderID", v.Folder.ID).String())
//line views/edit_folder.qtpl:27
	qw422016.N().S(`">
                                    `)
//line views/edit_folder.qtpl:28
	qw422016.E().S(v.Folder.Name)
//line views/edit_folder.qtpl:28
	qw422016.N().S(`
                                </a>
                            </h4>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="u-scroll-wrapper__body p-6">
            <div class="card w-100 mb-6">
                <div class="card-header">
                    <div class="bc-toolbar">
                        <div class="bc-toolbar-left">
                            <div class="bc-toolbar-item">Edit `)
//line views/edit_folder.qtpl:41
	qw422016.E().S(v.Folder.Name)
//line views/edit_folder.qtpl:41
	qw422016.N().S(`</div>
                        </div>
                        <div class="bc-toolbar-right">
                            <div class="bc-toolbar-item">
                                <form action="`)
//line views/edit_folder.qtpl:45
	qw422016.E().S(c.PathTo("delete_folder", "folderID", v.Folder.ID).String())
//line views/edit_folder.qtpl:45
	qw422016.N().S(`" method="POST" id="delete-folder">
                                    <input type="hidden" name="_method" value="DELETE">
                                    `)
//line views/edit_folder.qtpl:47
	qw422016.N().S(c.CSRFTag)
//line views/edit_folder.qtpl:47
	qw422016.N().S(`
                                    <button
                                        class="btn btn-link btn-link-muted"
                                        data-toggle="modal"
                                        data-target="#confirm-delete-folder"
                                    >
                                        <i class="if if-delete"></i>
                                        <span class="btn-text">Delete folder</span>
                                    </button>
                                </form>
                            </div>
                            <div class="bc-toolbar-item">
                                <a class="btn btn-link btn-link-muted" href="`)
//line views/edit_folder.qtpl:59
	qw422016.E().S(c.PathTo("folder", "folderID", v.Folder.ID).String())
//line views/edit_folder.qtpl:59
	qw422016.N().S(`">
                                    <i class="if if-close"></i>
                                    <span class="btn-text">Discard changes</span>
                                </a>
                            </div>
                            <div class="bc-toolbar-item">
                                <button class="btn btn-primary" data-submit-target="#update-folder">
                                    <i class="if if-check"></i>
                                    <span class="btn-text">Save changes</span>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    <form action="`)
//line views/edit_folder.qtpl:74
	qw422016.E().S(c.PathTo("update_folder", "folderID", v.Folder.ID).String())
//line views/edit_folder.qtpl:74
	qw422016.N().S(`" method="POST" id="update-folder">
                        <input type="hidden" name="_method" value="PUT">
                        `)
//line views/edit_folder.qtpl:76
	qw422016.N().S(c.CSRFTag)
//line views/edit_folder.qtpl:76
	qw422016.N().S(`
                        <div class="form-group">
                            <div class="form-row form-group">
                                <label class="col-lg-3 col-xl-2 col-form-label" for="folder-name">Folder name</label>
                                <div class="col-lg-5 col-xl-4">
                                    `)
//line views/edit_folder.qtpl:81
	if err := v.ValidationErrors.Get("name"); err != nil {
//line views/edit_folder.qtpl:81
		qw422016.N().S(`
                                    <input class="form-control is-invalid" type="text" value="`)
//line views/edit_folder.qtpl:82
		qw422016.E().S(v.Folder.Name)
//line views/edit_folder.qtpl:82
		qw422016.N().S(`" id="folder-name" name="name" aria-invalid="true" aria-describedby="folder-name-invalid">
                                    <small class="invalid-feedback" id="folder-name-invalid">`)
//line views/edit_folder.qtpl:83
		qw422016.E().S(err.Error())
//line views/edit_folder.qtpl:83
		qw422016.N().S(`</small>
                                    `)
//line views/edit_folder.qtpl:84
	} else {
//line views/edit_folder.qtpl:84
		qw422016.N().S(`
                                    <input class="form-control" type="text" value="`)
//line views/edit_folder.qtpl:85
		qw422016.E().S(v.Folder.Name)
//line views/edit_folder.qtpl:85
		qw422016.N().S(`" id="folder-name" name="name">
                                    `)
//line views/edit_folder.qtpl:86
	}
//line views/edit_folder.qtpl:86
	qw422016.N().S(`
                                </div>
                            </div>
                            <div class="form-row form-group">
                                <label class="col-lg-3 col-xl-2 col-form-label" for="URL">
                                    <p>Public shareable link</p>
                                </label>
                                <div class="col-lg-7 col-xl-9">
                                    <code class="c-code">`)
//line views/edit_folder.qtpl:94
	qw422016.E().S(c.URLTo("share_folder", "folderID", v.Folder.ID, "folderSlug", v.Folder.Slug()).String())
//line views/edit_folder.qtpl:94
	qw422016.N().S(`</code>
                                    <p class="small form-text text-muted">Anyone with
                                    this automatically generated link can view the files
                                    in this folder.</p>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <div id="confirm-delete-folder" class="modal hide" aria-modal="true" aria-hidden="true" role="dialog">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="c-blank-slate c-blank-slate-muted">
                        <div class="bc-avatar">
                            <i class="if if-alert"></i>
                        </div>
                        <h4>
                            Are you sure you want to delete the folder
                            <br>
                            <strong>{{.Data.folder.Name}}</strong>
                            and its files?
                        </h4>
                        <p>You cannot undo this action or recover the files.</p>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-link" data-dismiss="modal">No, cancel</button>
                    <button class="btn btn-danger" data-submit-target="#delete-folder">Yes, delete this folder</button>
                </div>
            </div>
        </div>
    </div>
`)
//line views/edit_folder.qtpl:131
}

//line views/edit_folder.qtpl:131
func (v *EditFolder) WriteContent(qq422016 qtio422016.Writer, c *ctx.Ctx) {
//line views/edit_folder.qtpl:131
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/edit_folder.qtpl:131
	v.StreamContent(qw422016, c)
//line views/edit_folder.qtpl:131
	qt422016.ReleaseWriter(qw422016)
//line views/edit_folder.qtpl:131
}

//line views/edit_folder.qtpl:131
func (v *EditFolder) Content(c *ctx.Ctx) string {
//line views/edit_folder.qtpl:131
	qb422016 := qt422016.AcquireByteBuffer()
//line views/edit_folder.qtpl:131
	v.WriteContent(qb422016, c)
//line views/edit_folder.qtpl:131
	qs422016 := string(qb422016.B)
//line views/edit_folder.qtpl:131
	qt422016.ReleaseByteBuffer(qb422016)
//line views/edit_folder.qtpl:131
	return qs422016
//line views/edit_folder.qtpl:131
}
