// Code generated by qtc from "errors.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/errors.qtpl:1
package views

//line views/errors.qtpl:1
import "github.com/ugent-library/deliver/ctx"

//line views/errors.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/errors.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/errors.qtpl:4
type Forbidden struct{}

//line views/errors.qtpl:7
func (v *Forbidden) StreamTitle(qw422016 *qt422016.Writer, c *ctx.Ctx) {
//line views/errors.qtpl:7
	qw422016.N().S(`Forbidden`)
//line views/errors.qtpl:7
}

//line views/errors.qtpl:7
func (v *Forbidden) WriteTitle(qq422016 qtio422016.Writer, c *ctx.Ctx) {
//line views/errors.qtpl:7
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/errors.qtpl:7
	v.StreamTitle(qw422016, c)
//line views/errors.qtpl:7
	qt422016.ReleaseWriter(qw422016)
//line views/errors.qtpl:7
}

//line views/errors.qtpl:7
func (v *Forbidden) Title(c *ctx.Ctx) string {
//line views/errors.qtpl:7
	qb422016 := qt422016.AcquireByteBuffer()
//line views/errors.qtpl:7
	v.WriteTitle(qb422016, c)
//line views/errors.qtpl:7
	qs422016 := string(qb422016.B)
//line views/errors.qtpl:7
	qt422016.ReleaseByteBuffer(qb422016)
//line views/errors.qtpl:7
	return qs422016
//line views/errors.qtpl:7
}

//line views/errors.qtpl:9
func (v *Forbidden) StreamContent(qw422016 *qt422016.Writer, c *ctx.Ctx) {
//line views/errors.qtpl:9
	qw422016.N().S(`
    <div class="d-flex u-maximize-height">
        <div class="w-100 u-scroll-wrapper">
            <div class="u-scroll-wrapper__body p-4">
                <div class="c-blank-slate c-blank-slate-default">
                    <h1 class="my-6">403 - Forbidden</h1>
                    <img src="`)
//line views/errors.qtpl:15
	qw422016.E().S(c.AssetPath("/images/torentje-forbidden.png"))
//line views/errors.qtpl:15
	qw422016.N().S(`"
                        alt="Our Booktower Mascotte named Torentje is spotted trespassing."
                        style="min-height: 300px; max-height: 500px; display: block; width: auto;"
                    >
                    <p>
                        <strong>Oops, only librarians have access to the admin panel.</strong>
                    </p>
                    <p class="mt-4">
                        <em>
                            <span>Are you a librarian? Get in touch with&nbsp;<a
                            href="mailto:libservice@ugent.be">libservice@ugent.be</a>.</span>
                        </em>
                    </p>
                </div>
            </div>
        </div>
    </div>
`)
//line views/errors.qtpl:32
}

//line views/errors.qtpl:32
func (v *Forbidden) WriteContent(qq422016 qtio422016.Writer, c *ctx.Ctx) {
//line views/errors.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/errors.qtpl:32
	v.StreamContent(qw422016, c)
//line views/errors.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line views/errors.qtpl:32
}

//line views/errors.qtpl:32
func (v *Forbidden) Content(c *ctx.Ctx) string {
//line views/errors.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
//line views/errors.qtpl:32
	v.WriteContent(qb422016, c)
//line views/errors.qtpl:32
	qs422016 := string(qb422016.B)
//line views/errors.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
//line views/errors.qtpl:32
	return qs422016
//line views/errors.qtpl:32
}

//line views/errors.qtpl:35
type NotFound struct{}

//line views/errors.qtpl:38
func (v *NotFound) StreamTitle(qw422016 *qt422016.Writer, c *ctx.Ctx) {
//line views/errors.qtpl:38
	qw422016.N().S(`Not found`)
//line views/errors.qtpl:38
}

//line views/errors.qtpl:38
func (v *NotFound) WriteTitle(qq422016 qtio422016.Writer, c *ctx.Ctx) {
//line views/errors.qtpl:38
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/errors.qtpl:38
	v.StreamTitle(qw422016, c)
//line views/errors.qtpl:38
	qt422016.ReleaseWriter(qw422016)
//line views/errors.qtpl:38
}

//line views/errors.qtpl:38
func (v *NotFound) Title(c *ctx.Ctx) string {
//line views/errors.qtpl:38
	qb422016 := qt422016.AcquireByteBuffer()
//line views/errors.qtpl:38
	v.WriteTitle(qb422016, c)
//line views/errors.qtpl:38
	qs422016 := string(qb422016.B)
//line views/errors.qtpl:38
	qt422016.ReleaseByteBuffer(qb422016)
//line views/errors.qtpl:38
	return qs422016
//line views/errors.qtpl:38
}

//line views/errors.qtpl:40
func (v *NotFound) StreamContent(qw422016 *qt422016.Writer, c *ctx.Ctx) {
//line views/errors.qtpl:40
	qw422016.N().S(`
    <div class="d-flex u-maximize-height">
        <div class="w-100 u-scroll-wrapper">
            <div class="u-scroll-wrapper__body p-4">
                <div class="c-blank-slate c-blank-slate-default">
                    <h1 class="my-8">404 - Page Not Found</h1>
                    <img src="`)
//line views/errors.qtpl:46
	qw422016.E().S(c.AssetPath("/images/torentje-wrong-delivery.png"))
//line views/errors.qtpl:46
	qw422016.N().S(`"
                        alt="Our Booktower Mascotte named Torentje receives a faulty delivery."
                        style="min-height: 300px; max-height: 400px; display: block; width: auto;"
                    >
                    <p>
                        <strong>It&rsquo;s possible you visited an expired link.</strong>
                    </p>
                    <p class="mt-4">
                        <em>
                            <span>Deliver links automatically expire after one month.</span>
                            <span>Get in touch with the sender of this link if this is the case.</span>
                        </em>
                    </p>
                </div>
            </div>
        </div>
    </div>
`)
//line views/errors.qtpl:63
}

//line views/errors.qtpl:63
func (v *NotFound) WriteContent(qq422016 qtio422016.Writer, c *ctx.Ctx) {
//line views/errors.qtpl:63
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/errors.qtpl:63
	v.StreamContent(qw422016, c)
//line views/errors.qtpl:63
	qt422016.ReleaseWriter(qw422016)
//line views/errors.qtpl:63
}

//line views/errors.qtpl:63
func (v *NotFound) Content(c *ctx.Ctx) string {
//line views/errors.qtpl:63
	qb422016 := qt422016.AcquireByteBuffer()
//line views/errors.qtpl:63
	v.WriteContent(qb422016, c)
//line views/errors.qtpl:63
	qs422016 := string(qb422016.B)
//line views/errors.qtpl:63
	qt422016.ReleaseByteBuffer(qb422016)
//line views/errors.qtpl:63
	return qs422016
//line views/errors.qtpl:63
}
