version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
        - ./.env
    volumes:
      - ../..:/src:cached
    command: 
      - bash
      - -c
      - |
        cd /src
        go mod download -x
        bash -i -c 'nvm install'
        npm install
        tern status
        tern migrate
        sleep infinity
    depends_on:
      - db-app
      - minio

  oidc:
    image: ugentlib/mock-oidc-server
    restart: unless-stopped
    volumes:
      - ./oidc:/dist/.data
    env_file:
      - .env
    network_mode: service:app

  db-app:
    image: postgres:16-alpine
    restart: unless-stopped
    user: postgres
    volumes:
      - ../tmp/app-db/db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DATABASE: deliver
      POSTGRES_USER: deliver
      POSTGRES_PASSWORD: deliver
      PGPORT: 3151
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U deliver -d deliver"]
      interval: 30s
      timeout: 10s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2023-12-09T18-17-51Z
    command: server /data -address ":3171" --console-address ":3172"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ../tmp/minio:/data

  minio-mc:
    image: minio/mc
    depends_on:
      - minio
    command: >
      /bin/sh -c "sleep infinity"
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc config host add myminio http://minio:9000 minioadmin minioadmin;
      /usr/bin/mc mb myminio/deliver --ignore-existing;
      exit 0;
      "