// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/ugent-library/deliver/ent/file"
	"github.com/ugent-library/deliver/ent/folder"
	"github.com/ugent-library/deliver/ent/space"
)

// FolderCreate is the builder for creating a Folder entity.
type FolderCreate struct {
	config
	mutation *FolderMutation
	hooks    []Hook
}

// SetSpaceID sets the "space_id" field.
func (fc *FolderCreate) SetSpaceID(s string) *FolderCreate {
	fc.mutation.SetSpaceID(s)
	return fc
}

// SetName sets the "name" field.
func (fc *FolderCreate) SetName(s string) *FolderCreate {
	fc.mutation.SetName(s)
	return fc
}

// SetCreatedAt sets the "created_at" field.
func (fc *FolderCreate) SetCreatedAt(t time.Time) *FolderCreate {
	fc.mutation.SetCreatedAt(t)
	return fc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (fc *FolderCreate) SetNillableCreatedAt(t *time.Time) *FolderCreate {
	if t != nil {
		fc.SetCreatedAt(*t)
	}
	return fc
}

// SetUpdatedAt sets the "updated_at" field.
func (fc *FolderCreate) SetUpdatedAt(t time.Time) *FolderCreate {
	fc.mutation.SetUpdatedAt(t)
	return fc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (fc *FolderCreate) SetNillableUpdatedAt(t *time.Time) *FolderCreate {
	if t != nil {
		fc.SetUpdatedAt(*t)
	}
	return fc
}

// SetExpiresAt sets the "expires_at" field.
func (fc *FolderCreate) SetExpiresAt(t time.Time) *FolderCreate {
	fc.mutation.SetExpiresAt(t)
	return fc
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (fc *FolderCreate) SetNillableExpiresAt(t *time.Time) *FolderCreate {
	if t != nil {
		fc.SetExpiresAt(*t)
	}
	return fc
}

// SetID sets the "id" field.
func (fc *FolderCreate) SetID(s string) *FolderCreate {
	fc.mutation.SetID(s)
	return fc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (fc *FolderCreate) SetNillableID(s *string) *FolderCreate {
	if s != nil {
		fc.SetID(*s)
	}
	return fc
}

// SetSpace sets the "space" edge to the Space entity.
func (fc *FolderCreate) SetSpace(s *Space) *FolderCreate {
	return fc.SetSpaceID(s.ID)
}

// AddFileIDs adds the "files" edge to the File entity by IDs.
func (fc *FolderCreate) AddFileIDs(ids ...string) *FolderCreate {
	fc.mutation.AddFileIDs(ids...)
	return fc
}

// AddFiles adds the "files" edges to the File entity.
func (fc *FolderCreate) AddFiles(f ...*File) *FolderCreate {
	ids := make([]string, len(f))
	for i := range f {
		ids[i] = f[i].ID
	}
	return fc.AddFileIDs(ids...)
}

// Mutation returns the FolderMutation object of the builder.
func (fc *FolderCreate) Mutation() *FolderMutation {
	return fc.mutation
}

// Save creates the Folder in the database.
func (fc *FolderCreate) Save(ctx context.Context) (*Folder, error) {
	fc.defaults()
	return withHooks[*Folder, FolderMutation](ctx, fc.sqlSave, fc.mutation, fc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (fc *FolderCreate) SaveX(ctx context.Context) *Folder {
	v, err := fc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fc *FolderCreate) Exec(ctx context.Context) error {
	_, err := fc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fc *FolderCreate) ExecX(ctx context.Context) {
	if err := fc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (fc *FolderCreate) defaults() {
	if _, ok := fc.mutation.CreatedAt(); !ok {
		v := folder.DefaultCreatedAt()
		fc.mutation.SetCreatedAt(v)
	}
	if _, ok := fc.mutation.UpdatedAt(); !ok {
		v := folder.DefaultUpdatedAt()
		fc.mutation.SetUpdatedAt(v)
	}
	if _, ok := fc.mutation.ID(); !ok {
		v := folder.DefaultID()
		fc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (fc *FolderCreate) check() error {
	if _, ok := fc.mutation.SpaceID(); !ok {
		return &ValidationError{Name: "space_id", err: errors.New(`ent: missing required field "Folder.space_id"`)}
	}
	if _, ok := fc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Folder.name"`)}
	}
	if _, ok := fc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Folder.created_at"`)}
	}
	if _, ok := fc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Folder.updated_at"`)}
	}
	if _, ok := fc.mutation.SpaceID(); !ok {
		return &ValidationError{Name: "space", err: errors.New(`ent: missing required edge "Folder.space"`)}
	}
	return nil
}

func (fc *FolderCreate) sqlSave(ctx context.Context) (*Folder, error) {
	if err := fc.check(); err != nil {
		return nil, err
	}
	_node, _spec := fc.createSpec()
	if err := sqlgraph.CreateNode(ctx, fc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Folder.ID type: %T", _spec.ID.Value)
		}
	}
	fc.mutation.id = &_node.ID
	fc.mutation.done = true
	return _node, nil
}

func (fc *FolderCreate) createSpec() (*Folder, *sqlgraph.CreateSpec) {
	var (
		_node = &Folder{config: fc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: folder.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: folder.FieldID,
			},
		}
	)
	if id, ok := fc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := fc.mutation.Name(); ok {
		_spec.SetField(folder.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := fc.mutation.CreatedAt(); ok {
		_spec.SetField(folder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := fc.mutation.UpdatedAt(); ok {
		_spec.SetField(folder.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := fc.mutation.ExpiresAt(); ok {
		_spec.SetField(folder.FieldExpiresAt, field.TypeTime, value)
		_node.ExpiresAt = value
	}
	if nodes := fc.mutation.SpaceIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   folder.SpaceTable,
			Columns: []string{folder.SpaceColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: space.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SpaceID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := fc.mutation.FilesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   folder.FilesTable,
			Columns: []string{folder.FilesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeString,
					Column: file.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// FolderCreateBulk is the builder for creating many Folder entities in bulk.
type FolderCreateBulk struct {
	config
	builders []*FolderCreate
}

// Save creates the Folder entities in the database.
func (fcb *FolderCreateBulk) Save(ctx context.Context) ([]*Folder, error) {
	specs := make([]*sqlgraph.CreateSpec, len(fcb.builders))
	nodes := make([]*Folder, len(fcb.builders))
	mutators := make([]Mutator, len(fcb.builders))
	for i := range fcb.builders {
		func(i int, root context.Context) {
			builder := fcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*FolderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, fcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, fcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, fcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (fcb *FolderCreateBulk) SaveX(ctx context.Context) []*Folder {
	v, err := fcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (fcb *FolderCreateBulk) Exec(ctx context.Context) error {
	_, err := fcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (fcb *FolderCreateBulk) ExecX(ctx context.Context) {
	if err := fcb.Exec(ctx); err != nil {
		panic(err)
	}
}
