// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/ugent-library/dilliver/ent/file"
	"github.com/ugent-library/dilliver/ent/folder"
	"github.com/ugent-library/dilliver/ent/schema"
	"github.com/ugent-library/dilliver/ent/space"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	fileFields := schema.File{}.Fields()
	_ = fileFields
	// fileDescID is the schema descriptor for id field.
	fileDescID := fileFields[0].Descriptor()
	// file.DefaultID holds the default value on creation for the id field.
	file.DefaultID = fileDescID.Default.(func() string)
	folderFields := schema.Folder{}.Fields()
	_ = folderFields
	// folderDescID is the schema descriptor for id field.
	folderDescID := folderFields[0].Descriptor()
	// folder.DefaultID holds the default value on creation for the id field.
	folder.DefaultID = folderDescID.Default.(func() string)
	spaceFields := schema.Space{}.Fields()
	_ = spaceFields
	// spaceDescID is the schema descriptor for id field.
	spaceDescID := spaceFields[0].Descriptor()
	// space.DefaultID holds the default value on creation for the id field.
	space.DefaultID = spaceDescID.Default.(func() string)
}
