name: Cypress Tests

on:
  schedule:
    - cron: '30 7 * * *'
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          config-file: cypress/cypress.config.ts
          record: true
          config: video=true,retries=2
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
